import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  pager: {
    flex: 1,
  },
  scrollContainer: {
    flexGrow: 1,
  },
  page: {
    flex: 1,
  },
  settingsContent: {
    flex: 1,
    padding: 20,
    gap: 16,
  },
  affirmationPage: {
    overflow: 'hidden',
  },
  calendarPage: {
    overflow: 'hidden',
  },
  affirmationContent: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  affirmationImage: {
    width: '100%',
    height: '100%',
  },
  affirmationTextOverlay: {
    position: 'absolute',
    left: 20,
    right: 20,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  affirmationText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.55)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  affirmationActionRow: {
    marginTop: 216,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 72,
  },
  affirmationActionButton: {
    width: 42,
    height: 42,
    borderRadius: 21,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.55)',
  },
  affirmationActionIcon: {
    fontSize: 22,
    color: '#ffffff',
    lineHeight: 24,
  },
  affirmationHeader: {
    position: 'absolute',
    top: 18,
    right: 16,
    alignItems: 'flex-end',
    gap: 8,
  },
  topicPickerButton: {
    backgroundColor: 'rgba(0, 0, 0, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.55)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  topicPickerButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#ffffff',
  },
  topicPickerButtonIcon: {
    fontSize: 16,
    lineHeight: 18,
    color: '#ffffff',
  },
  affirmationSwipeHint: {
    position: 'absolute',
    bottom: 20,
    alignSelf: 'center',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 7,
    fontSize: 12,
    fontWeight: '600',
    color: '#ffffff',
    backgroundColor: 'rgba(0, 0, 0, 0.38)',
    textShadowColor: 'rgba(0, 0, 0, 0.55)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  topicModalBackdrop: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.55)',
  },
  topicModalSheet: {
    height: '94%',
    borderTopLeftRadius: 18,
    borderTopRightRadius: 18,
    backgroundColor: '#0f172a',
    padding: 16,
    gap: 12,
  },
  topicModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  topicModalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#f8fafc',
  },
  topicModalCloseText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#93c5fd',
  },
  topicList: {
    gap: 12,
    paddingBottom: 12,
  },
  topicCard: {
    height: 120,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.45)',
  },
  topicCardSelected: {
    borderColor: '#60a5fa',
    borderWidth: 2,
  },
  topicCardImage: {
    ...StyleSheet.absoluteFillObject,
  },
  topicCardOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(0, 0, 0, 0.38)',
    gap: 4,
  },
  topicCardTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#ffffff',
  },
  topicCardSelectionText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#bfdbfe',
  },
  backgroundModeRow: {
    flexDirection: 'row',
    gap: 8,
  },
  modeChip: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.6)',
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    alignItems: 'center',
  },
  modeChipSelected: {
    borderColor: '#60a5fa',
    backgroundColor: 'rgba(37, 99, 235, 0.32)',
  },
  modeChipText: {
    fontSize: 13,
    fontWeight: '600',
    color: '#e2e8f0',
  },
  backgroundSearchInput: {
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.6)',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: '#f8fafc',
  },
  backgroundSections: {
    gap: 14,
    paddingBottom: 12,
  },
  backgroundTagSection: {
    gap: 8,
  },
  backgroundTagBackButton: {
    alignSelf: 'flex-start',
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.6)',
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: 'rgba(30, 41, 59, 0.8)',
  },
  backgroundTagBackButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#bfdbfe',
  },
  backgroundTagTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#bfdbfe',
  },
  backgroundTagGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  backgroundTagCard: {
    width: '48%',
    aspectRatio: 1,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.45)',
    backgroundColor: '#0b1220',
  },
  backgroundTagPreviewGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    width: '100%',
    height: '100%',
  },
  backgroundTagPreviewImage: {
    width: '33.33%',
    height: '50%',
  },
  backgroundTagCardOverlay: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.25)',
  },
  backgroundTagCardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#ffffff',
    textTransform: 'capitalize',
    textShadowColor: 'rgba(0, 0, 0, 0.55)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  backgroundDetailsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  backgroundDetailCard: {
    width: '48%',
    minHeight: 120,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.45)',
  },
  backgroundCardsRow: {
    flexDirection: 'row',
    gap: 8,
    paddingRight: 8,
  },
  backgroundCard: {
    width: 180,
    height: 110,
    borderRadius: 12,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.45)',
  },
  backgroundCardSelected: {
    borderWidth: 2,
    borderColor: '#60a5fa',
  },
  backgroundCardImage: {
    ...StyleSheet.absoluteFillObject,
  },
  backgroundCardOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    backgroundColor: 'rgba(0, 0, 0, 0.34)',
    paddingHorizontal: 8,
    paddingVertical: 8,
    gap: 4,
  },
  backgroundCardTags: {
    fontSize: 11,
    fontWeight: '600',
    color: '#e2e8f0',
  },
  backgroundEmptyState: {
    fontSize: 14,
    color: '#cbd5e1',
    textAlign: 'center',
    paddingVertical: 20,
  },
  calendarContent: {
    flex: 1,
    width: '100%',
    height: '100%',
  },
  calendarImage: {
    width: '100%',
    height: '100%',
  },
  calendarTextOverlay: {
    position: 'absolute',
    left: 20,
    right: 20,
    top: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
  },
  calendarText: {
    fontSize: 24,
    fontWeight: '700',
    color: '#ffffff',
    textAlign: 'center',
    textShadowColor: 'rgba(0, 0, 0, 0.55)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 6,
  },
  calendarDateRow: {
    position: 'absolute',
    bottom: 20,
    left: 16,
    right: 16,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 10,
  },
  calendarDateText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#ffffff',
    textShadowColor: 'rgba(0, 0, 0, 0.55)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  calendarLogo: {
    width: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  calendarLogoText: {
    fontSize: 10,
    fontWeight: '700',
    color: '#111827',
  },
  loadingContainer: {
    paddingVertical: 16,
    alignItems: 'center',
    gap: 8,
  },
  loadingText: {
    color: '#4b5563',
  },
  title: {
    fontSize: 24,
    fontWeight: '700',
    color: '#111827',
  },
  subtitle: {
    fontSize: 14,
    color: '#4b5563',
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: '600',
    color: '#111827',
  },
  value: {
    marginTop: 4,
    fontSize: 13,
    color: '#4b5563',
  },
  timeInputs: {
    flexDirection: 'row',
    gap: 12,
  },
  inputBlock: {
    flex: 1,
    gap: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: '#d1d5db',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 16,
    color: '#111827',
  },
  status: {
    fontSize: 13,
    color: '#2563eb',
  },
  footer: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: '#d1d5db',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  pageIcons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  pageIcon: {
    fontSize: 16,
    color: '#9ca3af',
  },
  pageIconActive: {
    color: '#2563eb',
  },
  footerText: {
    fontSize: 12,
    color: '#6b7280',
  },
});
